x-mongodb-common-env: &mongodb-common-env
  MONGODB_INITDB_ROOT_USERNAME: root
  MONGODB_INITDB_ROOT_PASSWORD: example

x-pg-common-env: &pg-common-env
  POSTGRES_USER: ${PG_USER}
  POSTGRES_PASSWORD: ${PG_PASSWORD}
  POSTGRES_DB: ${PG_DB}

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  #db
  postgres-db:
    container_name: postgres_db
    image: postgres:15
    environment:
      <<: *pg-common-env
    ports:
      - '5434:${PG_PORT}'

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  #airflow
  airflow-webserver:
    build: ./infra/airflow-webserver
    container_name: airflow-webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: a1b2c3d4e5f6a7b8c9d0e1f2g3h4i5j6
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    ports:
      - "8080:8080"
    command: "webserver"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./queries:/opt/aiflow/sql   
      - ./tasks:/opt/airflow/tasks 


  airflow-scheduler:
    build: ./infra/airflow-scheduler
    container_name: airflow-scheduler
    depends_on:
      - postgres
    environment:
      <<: [*pg-common-env, *mongodb-common-env]
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: a1b2c3d4e5f6a7b8c9d0e1f2g3h4i5j6
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: 27017

      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}

      AIRFLOW_CONN_POSTGRES_DEFAULT: "postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB}"
    restart: always
    command: 
      - scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./queries:/opt/airflow/sql   
      - ./tasks:/opt/airflow/tasks

volumes:
  postgres_data:
  mongodb_data:



